### ISSUE TITLE
SCA On web seams to not work

### ISSUE THREAD

**Issue by nmacherey** [ezet/stripe-sdk#35]
Could you precise what should be the return URL for Web SCA ?
The url provided for android and iOS is not working.

Should I put any URL compatible with the web hosted URL. ?

thanks a lot
nicolas

**Comment by josxha** [comment]
@nmacherey The SCA process opens a web page on which the transaction must be confirmed. The user is then redirected back to the app. This is done via a so-called deep link. If no own link is set, the default link "stripesdk://3ds.stripesdk.io" is used.

> Should I put any URL compatible with the web hosted URL. ?

Examples for a custom link are:
- your-app://stripe.payment
- com.your-website.your-app://stripesdk.io

However, this link should be such that no other app uses it. More details about deep linking (here specifically for Android) can be found at https://developer.android.com/training/app-links/deep-linking

However, if your application does not respond to a link, the problem is probably in your **AndroidManifest.xml** or **Info.plist** file. In this case it might be worth checking the instructions in the [ReadMe.me](https://github.com/ezet/stripe-sdk#android) file again. Be sure that the URL in those files matches the provided url in your instance of the Stripe() class. 
If your problem does not resolve, more details about your implementation or a sample project would be helpful to reproduce your error.

I have successfully implemented the implementation on Android. So it should also work for you on Android.
Under iOS 13+ there is already an open error message at https://github.com/ezet/stripe-sdk/issues/19#issuecomment-608313702 .

**Comment by alexismoret** [comment]
Hello,
I recently use a Deep-link that redirect to my app as the return url SCA, the future function confirmSetupIntentWithPaymentMethod works fine but never finished, even if the setup intent is confirmed. 
I'm running my app in Android X.
Any idea please ?

**Comment by ezet** [comment]
@alexismoret I think I'll need more details to help you, or some code. If the setup intent is confirmed, I don't see how the method isn't finished. Are you using await ?

**Comment by alexismoret** [comment]
Yes, I guess it's very strange but I think it's about that the app open stripe on chrome app to authenticate the intent and then return to my app by launching the "returnUrlForSca" which is a deep link, so maybe during the intent authentication the code is not running.

I have a FutureBuilder that take this future function:
```
Future<Map<String, dynamic>> saveNewCard() async {
    try {
      final paymentMethodId = await Payment().createPaymentMethodCard(_userCreditCard);
      final intent = await ApiRequest.post(context, "/user/cardwallet/setupintent");

      final confirmIntent = await Stripe.instance.confirmSetupIntentWithPaymentMethod(
          intent["ClientSecret"],
          paymentMethodId
      );
       // Never ended

      return confirmIntent;
    } catch(e) {
      return Future.error(e);
    }
}
```

This is my Stripe instance with the deep link : 
`Stripe.init(stripePublishableKey, returnUrlForSca: 'https://gfaim.page.link/h');`

When I test a Stripe card without authentication it works perfectly, else it will confirm the intent ( I can see that it is confirmed on Stripe ), but the Future is never ended

**Comment by ezet** [comment]
@alexismoret What does your AndroidManifest.xml look like? Just the intents section.

**Comment by ezet** [comment]
@alexismoret Could you try with a custom scheme? eg. `stripesdk://gfaim.page.link` 
Remember to change both the initialization and the android manifest. These should not be http/https URIs.

**Comment by nmacherey** [comment]
> @nmacherey The SCA process opens a web page on which the transaction must be confirmed. The user is then redirected back to the app. This is done via a so-called deep link. If no own link is set, the default link "stripesdk://3ds.stripesdk.io" is used.
> 
> > Should I put any URL compatible with the web hosted URL. ?
> 
> Examples for a custom link are:
> 
> * your-app://stripe.payment
> * com.your-website.your-app://stripesdk.io
> 
> However, this link should be such that no other app uses it. More details about deep linking (here specifically for Android) can be found at https://developer.android.com/training/app-links/deep-linking
> 
> However, if your application does not respond to a link, the problem is probably in your **AndroidManifest.xml** or **Info.plist** file. In this case it might be worth checking the instructions in the [ReadMe.me](https://github.com/ezet/stripe-sdk#android) file again. Be sure that the URL in those files matches the provided url in your instance of the Stripe() class.
> If your problem does not resolve, more details about your implementation or a sample project would be helpful to reproduce your error.
> 
> I have successfully implemented the implementation on Android. So it should also work for you on Android.
> Under iOS 13+ there is already an open error message at [#19 (comment)](https://github.com/ezet/stripe-sdk/issues/19#issuecomment-608313702) .

Thanks for your answer, my question is more or less regarding the web version for it... It works well on iOs and Android but on the web it never returns to the app. So what should the web url looks like ? 

Thanks

**Comment by alexismoret** [comment]
Now it works, that was just a problem of AndroidManifest.xml, Thanks ! 👍 

However, my deep link is created and managed by Firebase, so it can only be https://domain.page.link, so what is the impact to have an https scheme instead of stripesdk scheme ?
Another "small" problem is that when authentication is finished on stripe, it open the deep link and then android ask on which application to open the link, so it works very good ( as I expected ), but out of curiosity, is it possible to implement a "Go back action", instead of open a deep link ? I think it would be a better user experience than having to click a button to go back to the app, or may be set the authentication in a web view ? I don't know if all of this is possible but whatever, this are small details

**Comment by ezet** [comment]
> Now it works, that was just a problem of AndroidManifest.xml, Thanks ! 👍
> 
> However, my deep link is created and managed by Firebase, so it can only be https://domain.page.link, so what is the impact to have an https scheme instead of stripesdk scheme ?
> Another "small" problem is that when authentication is finished on stripe, it open the deep link and then android ask on which application to open the link, so it works very good ( as I expected ), but out of curiosity, is it possible to implement a "Go back action", instead of open a deep link ? I think it would be a better user experience than having to click a button to go back to the app, or may be set the authentication in a web view ? I don't know if all of this is possible but whatever, this are small details

Which applications do you have to chose from? If you get asked which app, its because there are multiple apps that are registered to handle that type of deep link. That might be one of the issues of using https instead of a custom scheme, not sure.

It's not possible to implement any other means of going back. A web view is actually worse, because web views do not support deep links. So it's not possible to automatically direct the user back to the app after finishing the SCA flow.

**Comment by ezet** [comment]
> Thanks for your answer, my question is more or less regarding the web version for it... It works well on iOs and Android but on the web it never returns to the app. So what should the web url looks like ?
> 
> Thanks

I have not tried, or thought of, how this works on web. I would like to support it, but as of now I'd have to say it is not supported. If you happen to find a solution or suggestions, please let me know :)

I guess, for web, the return URL should be the actual URL you want the user to be returned to after completion. In other words, it's just a regular return url, not a "deep link" url.

**Comment by ezet** [comment]
@alexismoret A deep-link using a custom scheme does not need to be managed by firebase. You can enter any URI you like, as long as the URIs in the manifest and Stripe.init() configuration match.

**Comment by ezet** [comment]
Web works

**Comment by vekexasia** [comment]
@ezet, I'm struggling as well to get this working on web. also it looks like I cant compile the example for web. Maybe i'm missing something.

**Comment by vekexasia** [comment]
@ezet, to add some context, Basically it seems that on web, the flow correctly launches the SCA authentication flow. I guess listening with uni-links is the issue.

**Comment by vodemn** [comment]
> Web works

Can you please tell, how to setup this plugin for web?
