### ISSUE TITLE
Does this support Flutter web?

### ISSUE THREAD

**Issue by long1eu** [ezet/stripe-sdk#41]

**Comment by josxha** [comment]
In my opinion, the package should work fine on the web because it is written 100% in Dart.
However, I personally have not tested it on the web yet, so I cannot speak with absolute certainty.

**Comment by ezet** [comment]
As @josxha says, there is nothing that explicitly prevents it from supporting web. Alas, I have not tested it either. I'd like it to be officially supported, and suggestions, bug reports and PRs for web support would be appreciated.

I think you would need to set the return url to an actual URL in that case, instead of a deep-link style url.

**Comment by long1eu** [comment]
I just tried it and it works perfectly.

Thanks for your work.

**Comment by ezet** [comment]
Great!

**Comment by vodemn** [comment]
> I just tried it and it works perfectly. Thanks for your work.
Can you please tell, how you've got if working?

**Comment by long1eu** [comment]
I suppose you first need to know how Stripe works as a product, the you can
use this link very easily. Check with Stripe Official documentation.
