### ISSUE TITLE
Very Hard to Setup ! , now i waste 8 hours for nothing in the end !!

### ISSUE THREAD

**Issue by imeDevelopers** [ezet/stripe-sdk#75]
not clear example ..
no `paymentRequestWithCardForm` as i understand [here](https://medium.com/@hamza39460/stripe-payments-in-flutter-cb2f9cb053d1)

what is the different between the payment Method and payment Intent ? , why i can't simply send request payment by card details and amount ? .. instead of all this options (native,api,browsers) what is this ?

i need to send http/https request contains my secret key and card details and the amount what i will pull from the card ..

your plugin is very stupid .. there's no need for all of this !!!

**Comment by eyoeldefare** [comment]
The guy is just too genius to understand regular developers like us understand his code. haha
He writes assembly code, what did you expect. He is too smart for this.

**Comment by Isakdl** [comment]
"what is the different between the payment Method and payment Intent"

You should read the Stripe api documentation to answer all these questions. This plugin is simply an implementation for the Stripe api. The reason for the payment intent is to help handle all different authentication flows that exists, such as SCA, 3dSecure etc. It also helps consolidate several different payment methods (cards, apple pay, google pay, wechat, alipay and more) into a single api endpoint. 

You should also NOT collect the card details your self and absolutely not handle them in your own backend unless you have a very good reason to do so. Simply because it will be very costly to do so, and you have to comply with a very long list of regulations.

Check out:
https://stripe.com/docs
https://stripe.com/docs/api

**Comment by CiriousJoker** [comment]
Also wtf is wrong with you. You don't just insult people on the internet because the free stuff they provide you with doesn't suit your needs.
